targets:
  $default:
    builders:
      isar_plus|isar_generator:
        generate_for:
          include:
            - lib/app/storage/saved_file_entity.dart
            - lib/app/storage/folder_entity.dart
